spring.application.name=Pathfinder
spring.datasource.url=jdbc:h2:file:./data/pathfinder-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
pathfinder.routing.default-algorithm=astar
pathfinder.routing.default-objective=distance
pathfinder.routing.balanced.distance-weight=0.5
pathfinder.routing.balanced.time-weight=0.5
pathfinder.routing.reference-speed-kph=40.0
pathfinder.routing.fallback-speed-kph=30.0
pathfinder.routing.speed-kph-by-highway.motorway=96.0
pathfinder.routing.speed-kph-by-highway.trunk=80.0
pathfinder.routing.speed-kph-by-highway.primary=56.0
pathfinder.routing.speed-kph-by-highway.secondary=48.0
pathfinder.routing.speed-kph-by-highway.tertiary=40.0
pathfinder.routing.speed-kph-by-highway.residential=30.0
pathfinder.routing.speed-kph-by-highway.service=24.0
pathfinder.routing.speed-kph-by-highway.living_street=16.0
pathfinder.routing.avoid-highway-multipliers.motorway=1.8
pathfinder.routing.avoid-highway-multipliers.trunk=1.5
pathfinder.routing.avoid-highway-multipliers.primary=1.25
pathfinder.routing.prefer-main-road-multipliers.primary=0.92
pathfinder.routing.prefer-main-road-multipliers.secondary=0.95
pathfinder.routing.prefer-main-road-multipliers.tertiary=0.97
pathfinder.search.default-limit=10
pathfinder.search.max-limit=50
